### ISSUE TITLE
Vertical energy component

### ISSUE THREAD

**Issue by tigikay** [PaulMcMillan-Astro/GalPot#2]
Are there any plans to have the program give out vertical energy components?

I am currently focused on looking at the z-component of energy for Gaia DR2 stars. Unfortunately not as proficient at C++ to change it or find the part of the code where the energy is calculated.

**Comment by PaulMcMillan-Astro** [comment]
That is not planned. The vertical energy can vary significantly over the orbit (see e.g. Binney & McMillan 2011).

If you wish to work out the current vertical energy then code to guide you comes in testGalPot (which calculates the potential) and findOrbitProperties, which contains examples of unit conversions.
