### ISSUE TITLE
Typos in GalPot.py

### ISSUE THREAD

**Issue by giulianoiorio** [PaulMcMillan-Astro/GalPot#4]
Hi Paul, 
I just realised that there is a typo in the declaration of the argtypes in the function Potential_and_derivatives in GalPot.py.

Essentially, the dPdz Pointer declaration is missing, so
Line 87 should be 
 lib.GalPot_Potential_and_derivatives.argtypes = [c_void_p,POINTER(c_double),POINTER(c_double),
                                                             POINTER(c_double),POINTER(c_double),POINTER(c_double),c_int]
instead of  
lib.GalPot_Potential_and_derivatives.argtypes = [c_void_p,POINTER(c_double),POINTER(c_double),
                                                             POINTER(c_double),POINTER(c_double),c_int].

**Comment by PaulMcMillan-Astro** [comment]
Fixed. Thanks for letting me know!
