### ISSUE TITLE
GalPot python wrapper example 2D potential array ordering

### ISSUE THREAD

**Issue by aywander** [PaulMcMillan-Astro/GalPot#7]
In the example shown in GalPotPythonExample.ipynb, in `In [12]`

``` Python
R_arr = np.linspace(0.1,10,100)
z_arr = np.linspace(0.1,10,100)
RRgrid, ZZgrid = np.meshgrid(R_arr,z_arr)
Pot = Phi.Potential(np.array(RRgrid).flatten(),np.array(ZZgrid).flatten())
Pot = Pot.reshape((len(R_arr),len(z_arr)))
```

when plotted works and looks correct (as seen in the output), but i think the last line should be `Pot = Pot.reshape((len(z_arr),len(R_arr)))` for it to work when the `len(R_arr)` and `len(z_arr)` are not equal.

**Comment by PaulMcMillan-Astro** [comment]
Thanks for spotting that. I absolutely loathe python indexing when it comes to these plots.

I have replaced (len(R_arr),len(z_arr)) with RRgrid.shape for a bit more clarity.
