### ISSUE TITLE
Discontinuity in LfromRc()

### ISSUE THREAD

**Issue by ybillchen** [PaulMcMillan-Astro/GalPot#9]
Hi Paul,

The `LfromRc()` function has a discontinuity at `R = Rmin` (See figure below). I think this is due to the incorrect coefficient in `src/GalPot.cc`, line 781:
```c++
g3h = 0.5*(3.-gamma);
```
Since we have `density ~ R^-gamma` when `R << Rmin`, I think the  correct relation is `dlnL/dlnR = 0.5(4-gamma)`. Therefore, this line should be corrected as
```c++
g3h = 0.5*(4.-gamma);
```
I plot below the `L-R` relation and `(dlnL/dlnR)-R` relation to illustrate the discontinuity and how to solve it.

![GalPot_LfromRc_test](https://user-images.githubusercontent.com/33487119/129452295-b9a659c2-0b3b-4950-837d-bb699f55343f.png)

This figure is based on the `PJM17_best.Tpot`. Similarly, line 780 also needs to be changed.

Thanks,
Bill Chen

**Comment by PaulMcMillan-Astro** [comment]
You are absolutely correct. Many apologies for not fixing this when you brought it up - I was on holiday and never got back to it once I returned. Fixed now, with many thanks.
